print ("HELLO THERE, LET ME INTRODUCE MYSLEF, I AM A.P.A.B MY NAME STANDS FOR,AUTOMATED, PYTHON, ASSISTANT, BOT, I WAS CREATED TO HELP YOU CODE YOUR FIRST PYTHON PROJECT!")
import time
time.sleep(1)
print ("NOW WHAT IS YOUR NAME?")
text = input("Response:")
print ("HELLO THANK YOU FOR YOUR CO-OPERATION, NOW LETS GET STARTED!")